apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deplo
  name: nginx-deplo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deplo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deplo
    spec:
      containers:
      - image: nginx
        name: nginx
